"""added disease table

Revision ID: 061b8906f2de
Revises: 822afdfbec5d
Create Date: 2022-11-29 13:47:48.553559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "061b8906f2de"
down_revision = "822afdfbec5d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disease",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("diesease_type", sa.String(), nullable=False),
        sa.Column("symptoms", sa.String(), nullable=False),
        sa.Column("afftected_plants", sa.JSON(), nullable=False),
        sa.Column("images", sa.JSON(), nullable=False),
        sa.Column("causes", sa.String(), nullable=False),
        sa.Column("organic_control", sa.String(), nullable=False),
        sa.Column("chemical_control", sa.String(), nullable=False),
        sa.Column("preventive_measures", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_disease_id"), "disease", ["id"], unique=False)
    # op.drop_table('spatial_ref_sys')
    op.alter_column(
        "crop", "description", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.alter_column("farm", "crop", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("farm", "crop", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "crop", "description", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_index(op.f("ix_disease_id"), table_name="disease")
    op.drop_table("disease")
    # ### end Alembic commands ###
