"""crop_stage

Revision ID: 5b705a374a2a
Revises: 02dd91b97c40
Create Date: 2022-12-02 14:00:37.788317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5b705a374a2a"
down_revision = "02dd91b97c40"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crop_stages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("crop", sa.String(), nullable=False),
        sa.Column("stages", sa.String(), nullable=True),
        sa.Column("days", sa.Float(), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("tasks", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["crop"],
            ["crop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crop_stages_id"), "crop_stages", ["id"], unique=False)
    # op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('spatial_ref_sys',
    # sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    # sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    # sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    # sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    # )
    op.drop_index(op.f("ix_crop_stages_id"), table_name="crop_stages")
    op.drop_table("crop_stages")
    # ### end Alembic commands ###
